using System.Collections.Generic;

namespace Pagamento2Net
{
    internal class OcorrênciasBradesco : OcorrênciaParser
    {
        private Dictionary<string, string> values = new Dictionary<string, string>()
        {
            {"AA","Arquivo duplicado"},
            {"AB","Data limite para desconto, sem valor correspondente"},
            {"AC","Tipo de serviço inválido"},
            {"AD","Modalidade de pagamento inválida"},
            {"AE","Tipo de inscrição e identificação do cliente pagador incompatíveis"},
            {"AF","Valores não numéricos ou zerados"},
            {"AG","Tipo de inscrição e identificação do favorecido incompatíveis"},
            {"AJ","Tipo de movimento inválido"},
            {"AL","Banco, agência ou conta inválido"},
            {"AM","Agência do favorecido inválida"},
            {"AN","Conta corrente do favorecido inválida"},
            {"AO","Nome do favorecido não informado"},
            {"AQ","Tipo de moeda inválido"},
            {"AT","CGC/CPF do favorecido inválido"},
            {"AU","Endereço do favorecido não informado"},
            {"AX","CEP do favorecido inválido"},
            {"AY","Alteração inválida; Banco anterior Bradesco"},
            {"AZ","Código de Banco do favorecido inválido"},
            {"BD","Pagamento agendado"},
            {"BE","Hora de gravação inválida"},
            {"BF","Identificação da empresa no Banco inválida"},
            {"BG","CGC/CPF do pagador inválido"},
            {"BH","Tipo de inscrição do cliente favorecido inválido"},
            {"BI","Data de vencimento inválida ou não preenchida"},
            {"BJ","Data de emissão do documento inválida"},
            {"BK","Tipo de inscrição do cliente favorecido não pemitido"},
            {"BL","Data limite para desconto inválida"},
            {"BM","Data para efetivação do pagamento inválida"},
            {"BN","Data para efetivação anterior a do processamento"},
            {"BO","Cliente não cadastrado"},
            {"BP","Identificação de Título Bradesco divergente da original"},
            {"BQ","Data do documento posterior ao vencimento"},
            {"BT","Desautorização efetuada"},
            {"BU","Alteração efetuada"},
            {"BV","Exclusão efetuada"},
            {"BW","Pagamento efetuado"},
            {"CD","Código de barras - valor do título divergente/inválido"},
            {"F0","Agendamento em atraso; não permitido pelo convênio"},
            {"F1","Tentativa de Agendamento com desc. Fora do Prazo"},
            {"F3","Tentativa de alteração inválida; confirmação de débito já efetuada"},
            {"F4","Falta registro trailler"},
            {"F5","Valor do trailler não confere"},
            {"F6","Quantidade de registros do trailler não confere"},
            {"F7","Tentativa de alteração inválida; pagamento já enviado ao Bradesco Instantâneo"},
            {"F8","Pagamento enviado após o horário estipulado"},
            {"F9","Tentativa de inclusão de registro existente em histórico"},
            {"FA","Código de origem inválido"},
            {"FB","Data de gravação do arquivo inválida"},
            {"FC","Tipo de documento inválido"},
            {"FD","Valor da parcela inválida"},
            {"FE","Número de pagamento inválido"},
            {"FF","Valor do desconto sem data limite"},
            {"FG","Data limite para desconto posterior ao vencimento"},
            {"FH","Falta número e/ou série do documento"},
            {"FI","Exclusão de agendamento não disponível"},
            {"FJ","Soma dos valores não confere"},
            {"FK","Falta valor de pagamento"},
            {"FL","Modalidade de pagamento inválida para o contrato"},
            {"FM","Código de movimento inválido"},
            {"FN","Tentativa de inclusão de registro existente"},
            {"FO","Tentativa de alteração para registro inexistente"},
            {"FP","Tentativa de efetivação de agendamento não disponível"},
            {"FQ","Tentativa de desautorização de agendamento não disponível"},
            {"FR","Autorização de agendamento sem data de efetivação e sem data de vencimento"},
            {"FS","Título em agendamento; Pedido de confirmação"},
            {"FT","Tipo de inscrição do cliente pagador inválido"},
            {"FU","Contrato inexistente ou inativo"},
            {"FV","Cliente com convênio cancelado"},
            {"FW","Valor autorizado inferior ao original"},
            {"FX","Está faltando registro header"},
            {"FZ","Valor autorizado não confere para pagamento em atraso"},
            {"GA","Tipo de DOC/TED inválido"},
            {"GB","Número do DOC/TED inválido"},
            {"GC","Finalidade do DOC/TED inválida ou inexistente"},
            {"GD","Conta corrente do favorecido encerrada/bloqueada"},
            {"GE","Conta corrente do favorecido não recadastrada"},
            {"GF","Inclusão de pagamento via modalidade 30 não permtida"},
            {"GG","Campo livre do código de barras (linha digitável) inválido"},
            {"GH","Dígito verificador do código de barras inválido"},
            {"GI","Código da moeda da linha digitável inválido"},
            {"GJ","Conta poupança do favorecido inválida"},
            {"GK","Conta poupança do favorecido não recadastrada"},
            {"GL","Conta poupança do favorecido não encontrada"},
            {"GM","Pagamento 3 (três) dias após o vencimento"},
            {"GN","Conta complementar inválida"},
            {"GO","Inclusão de DOC/TED para Banco 237 não permitido"},
            {"GP","CGC/CPF do favorecido divergente do cadastro do Banco"},
            {"GQ","Tipo de DOC/TED não permitido via sistema eletrônico"},
            {"GR","Alteração inválida; pagamento já enviado a agência pagadora"},
            {"GS","Limite de pagamento excedido. Fale com o Gerente da sua agência"},
            {"GT","Limite vencido/vencer em 30 dias"},
            {"GU","Pagamento agendado por aumento de limite ou redução no total autorizado"},
            {"GV","Cheque OP estornado conforme pedido"},
            {"GW","Conta corrente ou conta poupança com razão não permitida para efetivação de crédito"},
            {"GX","Cheque OP com data limite vencida"},
            {"GY","Conta poupança do favorecido encerrada/bloqueada"},
            {"GZ","Conta corrente do pagador encerrada/bloqueada"},
            {"HA","Agendado, débito sob consulta de saldo"},
            {"HB","Pagamento não efetuado, saldo insuficiente"},
            {"HC","Pagamento não efetuado, além de saldo insuficiente, conta com cadastro no DVL"},
            {"HD","Pagamento não efetuado, além de saldo insuficiente, conta bloqueada"},
            {"HE","Data de vencto/pagto fora do prazo de operação do banco"},
            {"HF","Processado e debitado"},
            {"HG","Processado e não debitado por saldo insuficiente"},
            {"HI","Cheque OP emitido nesta data"},
            {"JA","Código de lançamento inválido"},
            {"JB","DOC/TED/Títulos devolvidos e estornados"},
            {"JC","Modalidade alterada de 07/CIP, para 08/STR"},
            {"JD","Modalidade alterada de 07/CIP, para 03/DOC COMPE"},
            {"JE","Modalidade alterada de 08/STR para 07/CIP"},
            {"JF","Modalidade alterada de 08/STR para 03/COMPE"},
            {"JG","Alteração de modalidade via arquivo não permitido"},
            {"JH","Horário de consulta de saldo após encerramento rotina"},
            {"JI","Modalidade alterada de 01/Crédito em conta para 05/Crédito em conta real time"},
            {"JJ","Horário de agendamento inválido"},
            {"JK","Tipo de conta - modalidade DOC/TED - inválido"},
            {"JL","Título agendado/descontado"},
            {"JM","Alteração não permitida, título antecipado/descontado"},
            {"JN","Modalidade Alter. De 05/Crédito em conta real time para 01/Crédito em conta"},
            {"JO","Exclusão não permitida título antecipado/descontado"},
            {"JP","Pagamento com limite TED excedido. Fale com o gerente da sua agência para autorização"},
            {"KO","Autorização para débito em conta"},
            {"KP","Cliente pagador não cadastrado no PAGFOR"},
            {"KQ","Modalidade inválida para pagador em teste"},
            {"KR","Banco destinatário não operante nesta data"},
            {"KS","Modalidade alterada de DOC para TED"},
            {"KT","Dt. Efetivação alterada p/ próximo MOVTO. **TRAG"},
            {"KV","CPF/CNPJ do investidor inválido ou inexistente"},
            {"KW","Tipo de inscrição investidor inválido ou inexistente"},
            {"KX","Nome do investidor inexistente"},
            {"KZ","Código do investidor inexistente"},
            {"LA","Agendado sob lista de débito"},
            {"LB","Pagamento não autorizado sob lista de débito"},
            {"LC","Lista com mais de uma modalidade"},
            {"LD","Lista com mais de uma data de pagamento"},
            {"LE","Número de lista duplicado"},
            {"LF","Lista de débito vencida e não autorizada"},
            {"LG","Conta salário não permitida para este convênio"},
            {"LH","Código de lançamento inválido para conta salário"},
            {"LI","Finalidade do DOC/TED inválida para salário"},
            {"LJ","Conta salário obrigatória para este código de lançamento"},
            {"LK","Tipo de conta do favorecido inválida"},
            {"LL","Nome do favorecido inconsistente"},
            {"LM","Número de lista de débito inválido"},
            {"MA","Tipo conta inválida para finalidade"},
            {"MB","Conta crédito investimento inválida/inexistente"},
            {"MC","Conta débito investimeto inválida/inexistente"},
            {"MD","Titularidade diferente para tipo de conta"},
            {"ME","Data de pagamento alterada devido a feriado local"},
            {"MF","Alegação efetuada"},
            {"MG","Alegação não efetuada. Motivo da alegação/reconhecimento da dívida inconsistente"},
            {"MH","Autorização não efetuada. Código de reconhecimento da dívida não permitido."},
            {"NC","Código identificador inválido"},
            {"TR","Ag/conta do favorecido alterada por transferência de agência"},
            {"YA","Título não encontrado"},
            {"ZE","Título bloqueado na base"},
            {"ZF","Sistema em contingência - título valor maior que referência"},
            {"ZG","Sistema em contingência - título vencido"},
            {"ZH","Sistema em contingência - título indexado"},
            {"ZI","Beneficiário divergente"},
            {"ZJ","Limite de pagamentos parciais excedido"},
            {"ZK","Boleto já liquidado"},
        };

        public override Dictionary<string, string> Ocorrências { get => values; set => values = value; }
    }
}